### ISSUE TITLE
What is the goal of this project

### ISSUE THREAD

**Issue by kant2002** [kartoun/text-nailing#1]
subj

**Comment by janithb** [comment]
I'm also wondering the same. Recently got a contributor request anyway.

**Comment by kartoun** [comment]
The goal of the project is to extend the ability of extracting features from text, beyond smoking statuses and sleep disorders (see: http://interactions.acm.org/archive/view/november-december-2017/text-nailing).

I hope that the collaborators will find a way to generalize the code, so it could be effective to the extraction of many additional medical conditions. Later on, perhaps propose approaches to extract efficiently data from other sources of information (e.g., news sites, books not related to health).
